# --- Gateway Connection ---
gateways:
  databricks:
    connection:
      type: databricks
      server_hostname: "{{ env_var('DATABRICKS_HOSTNAME') }}"
      http_path: "{{ env_var('DATABRICKS_HTTPATH') }}"
      access_token:  "{{ env_var('DATABRICKS_TOKEN') }}"

default_gateway: databricks

# --- Model Defaults ---
model_defaults:
  dialect: databricks
  start: 2025-08-29
  cron: '@daily'

# --- Linting Rules ---
linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion

# --- CI/CD BOT CONFIGURATION ---
# This section defines the bot's behavior.
cicd_bot:
  type: github
  merge_method: squash
  users:
  - username: arebac_the_approver
    github_username: arebac  # The GitHub handle of your dummy/approver account
    roles:
      - required_approver