# --- Gateway Connection ---
gateways:
  databricks:
    connection:
      type: databricks
      server_hostname: "{{ env_var('DATABRICKS_HOSTNAME') }}"
      http_path: "{{ env_var('DATABRICKS_HTTPATH') }}"
      access_token:  "{{ env_var('DATABRICKS_TOKEN') }}"

default_gateway: databricks

# --- Model Defaults ---
model_defaults:
  dialect: databricks
  start: 2025-08-29
  cron: '@daily'

# --- Linting Rules ---
linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion

# --- CI/CD BOT CONFIGURATION ---
# This section enables the CI/CD bot and specifies its type.
cicd_bot:
  type: github

# --- GITHUB INTEGRATION SETTINGS ---
# This section defines the specific behavior for the GitHub bot.
github:
  merge_method: squash
  required_approvers:
    - 'arebac'
    - 'another_approver_username'