# --- Gateway Connection ---
gateways:
  databricks:
    connection:
      type: databricks
      server_hostname: "{{ env_var('DATABRICKS_HOSTNAME') }}"
      http_path: "{{ env_var('DATABRICKS_HTTPATH') }}"
      access_token:  "{{ env_var('DATABRICKS_TOKEN') }}"

default_gateway: databricks

# --- Model Defaults ---
model_defaults:
  dialect: databricks
  start: 2025-08-29
  cron: '@daily'

# --- Linting Rules ---
linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion

# --- CI/CD BOT CONFIGURATION ---
# This section defines the bot's behavior.
cicd_bot:
  type: github
  # Setting this to false (or omitting it) enables the "approve-to-deploy" workflow.
  # This is the key setting from the video.
  enable_deploy_command: false
  # You can customize the merge method if you like.
  merge_method: none
  # Ensure this matches your production branch name in GitHub.
  prod_branch_name: main