# --- Gateway Connection ---
gateways:
  databricks:
    connection:
      type: databricks
      server_hostname: "{{ env_var('DATABRICKS_HOSTNAME') }}"
      http_path: "{{ env_var('DATABRICKS_HTTPATH') }}"
      access_token:  "{{ env_var('DATABRICKS_TOKEN') }}"

default_gateway: databricks

# --- Model Defaults ---
model_defaults:
  dialect: databricks
  start: 2025-08-29
  cron: '@daily'

# --- Linting Rules ---
linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion

# --- CI/CD BOT CONFIGURATION ---
# This is the correct location for these rules
cicd_bot:
  type: github
  # To enable "approve-to-deploy", this must be false or omitted (default is false)
  enable_deploy_command: false
  # Other settings you might want:
  merge_method: squash
  prod_branch_name: main  # Or whatever your production branch is named

users:
- username: yessir
  github_username: arebac
  roles:
    - required_approver