name: SQLMesh Bot
run-name: 🚀SQLMesh Bot 🚀

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  pull_request_review:
    types:
      - submitted
      - dismissed

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  sqlmesh-bot: # Changed 'sqlmesh' to 'sqlmesh-bot' to be more descriptive
    name: SQLMesh CI/CD Bot
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      checks: write
      pull-requests: write
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Checkout Code
        uses: actions/checkout@v4
        # The complex 'ref' is not needed; the action defaults to the correct PR code.

      - name: Install Dependencies
        run: pip install -r requirements.txt
        shell: bash

      - name: Run CI/CD Bot
        run: sqlmesh_cicd -p ${{ github.workspace }} github --token ${{ secrets.GITHUB_TOKEN }} run-all
        env:
          # THIS IS THE FIX: Pass secrets as environment variables to the command
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HTTPATH: ${{ secrets.DATABRICKS_HTTPATH }}