name: SQLMesh Bot
run-name: 🚀SQLMesh Bot 🚀

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  pull_request_review:
    types:
      - submitted
      - dismissed

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  sqlmesh-bot:
    name: SQLMesh Actions Workflow
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      checks: write
      pull-requests: write
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Checkout Code
        uses: actions/checkout@v4
        # Simplified this step for best practice

      - name: Install Dependencies
        run: pip install -r requirements.txt
        shell: bash

      - name: Run CI/CD Bot
        run: sqlmesh_cicd -p ${{ github.workspace }} github --token ${{ secrets.GITHUB_TOKEN }} run-all
        env:
          # This provides the variables that your config.yaml is expecting
          DATABRICKS_HOSTNAME: ${{ secrets.DATABRICKS_HOSTNAME }}
          DATABRICKS_HTTPATH: ${{ secrets.DATABRICKS_HTTPATH }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}